auctions/urls.py
from django.urls import path

from . import views

app_name ="auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("alllistings", views.alllistings, name="alllistings"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listings/<str:listing_title>", views.listing, name="title"),
    path("create", views.create, name="create_listing"),
    path("userlisting", views.userlisting, name="user_listing"),
    path("deletelisting/<listing_id>", views.deletelisting, name="deletelisting"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("delete/<watchlist_id>",views.delete,name='delete'),
    path("category",views.category,name='category'),
    path("fashion",views.fashion,name='fashion'),
    path("toys",views.toys,name='toys'),
    path("electronics",views.electronics,name='electronics'),
    path("home",views.home,name='home'),
    path("uncategorized",views.uncategorized,name='uncategorized'),
    path("error", views.error, name="error"),

]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.db import models


class User(AbstractUser):
    pass 

             
    
class Listing(models.Model):
    UNCATEGORIZED = 'UN'
    FASHION = 'FA'
    TOYS = 'TO'
    ELECTRONIC = 'EL'
    HOME = 'HO'
    category = [
        (UNCATEGORIZED, 'Uncategorized'),
        (FASHION, 'Fashion'),
        (TOYS, 'Toys'),
        (ELECTRONIC, 'Electronics'),
        (HOME, 'Home'),
    ]
    
    category = models.CharField(
        max_length=2,
        choices=category,
        default=UNCATEGORIZED,
    )
    title = models.CharField(max_length=150)
    end_list = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)
    starting_bid = models.IntegerField(blank=True, null=True)
    current_bid = models.IntegerField(blank=True, null=True, default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    image_URL = models.CharField(max_length=255, null=True, blank=True)
        
    def __str__(self):
        return f"{self.title}"


class Bid (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=150, null=True)
    new_bid = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.title}: {self.new_bid}"  
        
        

class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return f"{self.user} {self.title}"
                
      
        
class Comment (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=150, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.title} ({self.comment})"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django import forms
from django.forms import ModelForm
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse


from .models import User, Listing, Bid, Comment, Watchlist

        
        
class NewListing(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'category', 'description', 'starting_bid', 'image_URL']
        
class NewComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        
class NewBid(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['new_bid']  


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")
       
        
def index(request):    
    listings = Listing.objects.all() 
    active_listings = []
    for i in range(len(listings)):
        active = listings[i]
        if active.end_list == False:
            active_listings.append(active)  
    
    return render(request, "auctions/index.html", {
        "listings": active_listings
    })  
      


def alllistings(request):
    listings = Listing.objects.all()
    
    return render(request, "auctions/alllistings.html", {
        "listings": listings
    }) 
       

          
def listing(request, listing_title): 
    if request.method == "POST":
        user = request.user
            
        if user.is_authenticated:
        
            listing = Listing.objects.get(title=listing_title)
            active_list = Listing.objects.get(title=listing_title).end_list == False
            
            bid_form = NewBid(request.POST)
            form = NewComment(request.POST)
        
            watchlist_btn = request.POST.get('watchlist')
            if watchlist_btn == "Add to watchlist": 
                if active_list:
                    title = listing_title
                    id = listing.id
                    user = request.user 
                    watchlist = Watchlist.objects.filter(title=id, user=user)
                    if watchlist:
                        return render(request, "auctions/error.html", {"error": "This item is already in your watchlist"}) 
                    else:                
                        watchlist = Watchlist()
                        watchlist.user = request.user
                        watchlist.title = Listing.objects.get(title=title)
                        watchlist.save()
                        watchlist_id = watchlist.id 
                        return HttpResponseRedirect(reverse("auctions:title", args=(listing_title,)))
                else:
                    warning = "Auction is ended."
                    return render(request, "auctions/error.html", {"warning": warning})
                
            endlist_btn = request.POST.get('endlist')
            if endlist_btn == "end auction":
                if Listing.objects.get(title=listing_title).end_list == False:
                    title = listing_title 
                    item_to_end = Listing.objects.get(title=title)
                    item_to_end.end_list = True
                    item_to_end.save()
                    return HttpResponseRedirect(reverse("auctions:title", args=(listing_title,)))
       
                return HttpResponseRedirect(reverse("auctions:title", args=(listing_title,)))            
   
            bid_btn = request.POST.get('bid')
            if bid_btn == "Bid":
                if bid_form.is_valid():
                    if active_list:
                        bid = bid_form.save(commit=False)
                        bid.user = request.user 
                        bid.title = listing_title   
                        
                        if listing.current_bid > 0:
                            if bid.new_bid is not None:
                                if bid.new_bid > listing.current_bid:
                                    bid.save()
                                    listing.current_bid = Bid.objects.filter(title=listing_title).last().new_bid
                                    listing.save()                                     
                                    return HttpResponseRedirect(reverse("auctions:title", args=(listing_title,))) 
                                else:
                                    warning = "Bid must be greater than current bid"
                                    return render(request, "auctions/error.html", {"warning": warning})                    
                        else:
                            listing.current_bid = listing.starting_bid 
                            if bid.new_bid is not None:
                                if bid.new_bid > listing.current_bid:
                                    listing.current_bid = Bid.objects.filter(title=listing_title).last()
                                    bid.save()
                                    listing.save()
                                    return HttpResponseRedirect(reverse("auctions:title", args=(listing_title,))) 
                                else:
                                    warning = "Bid must be greater than starting bid"
                                    return render(request, "auctions/error.html", {"warning": warning}) 
                    else:
                        warning = "Auction is ended."
                        return render(request, "auctions/error.html", {"warning": warning})                                
            
            comment_btn = request.POST.get('new_comment')
            if comment_btn == "Submit": 
                if form.is_valid():
                    if active_list:
                        comments = form.save(commit=False)
                        comments.user = request.user 
                        comments.title = listing_title
                        user_comment = comments.comment
                        comments.save()
                        return HttpResponseRedirect(reverse("auctions:title", args=(listing_title,)))
                    else:
                        warning = "Auction is ended."
                        return render(request, "auctions/error.html", {"warning": warning}) 

        else:       
            return render(request, "auctions/login.html") 
        
    if request.method == "GET":
        listing = Listing.objects.get(title=listing_title)
        comments = Comment.objects.filter(title=listing_title)
        auctions_owner = Listing.objects.get(title=listing_title).user
        user = request.user 
               
        bid = Bid.objects.filter(title=listing_title)
        
        if bid: 
            listing.current_bid = Bid.objects.filter(title=listing_title).last().new_bid
            listing.save()
            
            sold = Listing.objects.get(title=listing_title).end_list == True
            if sold:
                title = Listing.objects.get(title=listing_title).title;
                winner = Bid.objects.filter(title=title).last().user 
                if winner == user:
                    return render(request, "auctions/listing.html", {
                        "listing": listing,
                        "bid_form":NewBid(),
                        "form": NewComment(),
                        "comments": comments,
                        "winner": winner
                    })
                    
            if auctions_owner == user:        
                return render(request, "auctions/listing.html", {
                "listing": listing,
                "bid_form":NewBid(),
                "form": NewComment(),
                "comments": comments,
                "owner": user
                })
                
            return render(request, "auctions/listing.html", {
            "listing": listing,
            "bid_form":NewBid(),
            "form": NewComment(),
            "comments": comments,
            "non_owner": user
            })
        
        else:        
            if auctions_owner == user:        
                return render(request, "auctions/listing.html", {
                "listing": listing,
                "bid_form":NewBid(),
                "form": NewComment(),

auctions/templates/auctions/alllistings.html
{% extends "auctions/layout.html" %}

{% block body %}	
    <div class="listings">
		<h2>All Listings</h2>
        {% for listing in listings %}
		<div>
			<div class="image-container">
				<img src="{{ listing.image_URL }}" class="listing-img">
			</div>
			<h4>
				{{ listing.title }}
			</h4>
			<div>
				{{ listing.description }}
			</div>
			 <div class="bid-box">
				<p><b>Starting bid: ${{ listing.starting_bid }}</b></p>
				<p><b>Current bid: ${{ listing.current_bid }}</b></p>
			 </div>
			 
			<a href="{% url 'auctions:title' listing.title %}" class="btn btn-primary">view details</a>
		</div>
        {% endfor %}		
    </div>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="my-container category">
	<h2>Select Category</h2>
	<a href="{% url 'auctions:fashion' %}" class="btn btn-info">Fashion</a>
	<a href="{% url 'auctions:toys' %}" class="btn btn-info">Toys</a>
	<a href="{% url 'auctions:electronics' %}" class="btn btn-info">Electronics</a>
	<a href="{% url 'auctions:home' %}" class="btn btn-info">Home</a>
	<a href="{% url 'auctions:uncategorized' %}" class="btn btn-info">Uncategorized</a>
</div>

{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="my-container">
        <h2>Create New Listing</h2>
    <form class="new-listing create-form" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-primary" type="submit" />
    </form>
</div>
{% endblock %}

auctions/templates/auctions/electronics.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="listings">
	<h2>All Listings in "electronics" Cetegory</h2>	
	{% for listing in listings %}
		<div>
			<div class="image-container">
				<img src="{{ listing.image_URL }}" class="listing-img">
			</div>
			<h4>
				{{ listing.title }}
			</h4>
			<div>
				{{ listing.description }}
			</div>
			 <div class="bid-box">
				<p><b>Starting bid: ${{ listing.starting_bid }}</b></p>
				<p><b>Current bid: ${{ listing.current_bid }}</b></p>
			 </div>
			 
			<a href="{% url 'auctions:title' listing.title %}" class="btn btn-primary">view details</a>
		</div>
	{% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}

{% block title %}
error
{% endblock %}

{% block body %}

	{% if warning_login %}
		<div class="alert alert-warning">
			<p>{{ warning }}</p>
		</div>
	{% endif %}

	{% if warning %}
		<div class="alert alert-warning">
			<p>{{ warning }}</p>
		</div>
	{% endif %}
		
    <div class="my-container">
		<p>{{ error }}</p>
    </div>

{% endblock %}

auctions/templates/auctions/fashion.html
{% extends "auctions/layout.html" %}

{% block body %}	
    <div class="listings">
		<h2>All Listings in "fashion" Cetegory</h2>
        {% for listing in listings %}
		<div>
			<div class="image-container">
				<img src="{{ listing.image_URL }}" class="listing-img">
			</div>
			<h4>
				{{ listing.title }}
			</h4>
			<div>
				{{ listing.description }}
			</div>
			 <div class="bid-box">
				<p><b>Starting bid: ${{ listing.starting_bid }}</b></p>
				<p><b>Current bid: ${{ listing.current_bid }}</b></p>
			 </div>
			 
			<a href="{% url 'auctions:title' listing.title %}" class="btn btn-primary">view details</a>
		</div>
        {% endfor %}		
    </div>
{% endblock %}

auctions/templates/auctions/home.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="listings">
	<h2>All Listings in "home" Cetegory</h2>	
	{% for listing in listings %}
		<div>
			<div class="image-container">
				<img src="{{ listing.image_URL }}" class="listing-img">
			</div>
			<h4>
				{{ listing.title }}
			</h4>
			<div>
				{{ listing.description }}
			</div>
			 <div class="bid-box">
				<p><b>Starting bid: ${{ listing.starting_bid }}</b></p>
				<p><b>Current bid: ${{ listing.current_bid }}</b></p>
			 </div>
			 
			<a href="{% url 'auctions:title' listing.title %}" class="btn btn-primary">view details</a>
		</div>
	{% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
			 <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:alllistings' %}">All Listings</a>
            </li>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:category' %}">Categories</a>
            </li>
			<li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create_listing' %}">Create Listing</a>
			</li>
            {% if user.is_authenticated %}
				<li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:user_listing' %}">Your Listings</a>
                </li>
				<li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
				<li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="my-container">
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post" class="my-form">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
</div>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="my-container">
	<h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post" class="my-form">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
</div>

{% endblock %}

auctions/templates/auctions/toys.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="listings">
    <h2>All Listings in "toys" Cetegory</h2>
        {% for listing in listings %}
		<div>
			<div class="image-container">
				<img src="{{ listing.image_URL }}" class="listing-img">
			</div>
			<h4>
				{{ listing.title }}
			</h4>
			<div>
				{{ listing.description }}
			</div>
			 <div class="bid-box">
				<p><b>Starting bid: ${{ listing.starting_bid }}</b></p>
				<p><b>Current bid: ${{ listing.current_bid }}</b></p>
			 </div>
			 
			<a href="{% url 'auctions:title' listing.title %}" class="btn btn-primary">view details</a>
		</div>
        {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/uncategorized.html
{% extends "auctions/layout.html" %}

{% block body %}	
    <div class="listings">
		<h2>All Listings in "uncategorized" Cetegory</h2>
        {% for listing in listings %}
		<div>
			<div class="image-container">
				<img src="{{ listing.image_URL }}" class="listing-img">
			</div>
			<h4>
				{{ listing.title }}
			</h4>
			<div>
				{{ listing.description }}
			</div>
			 <div class="bid-box">
				<p><b>Starting bid: ${{ listing.starting_bid }}</b></p>
				<p><b>Current bid: ${{ listing.current_bid }}</b></p>
			 </div>
			 
			<a href="{% url 'auctions:title' listing.title %}" class="btn btn-primary">view details</a>
		</div>
        {% endfor %}		
    </div>
{% endblock %}

auctions/templates/auctions/userlisting.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="listings">
<h2>Your listings</h2>

        {% for listing in listings %}
			 <div>
			 <div class="image-container">
				<img src="{{ listing.image_URL }}" class="listing-img">
			</div>
			<h4>
				{{ listing.title }}
			</h4>
			<div>
				{{ listing.description }}
			</div>
			 <div class="bid-box">
				<p><b>Starting bid: ${{ listing.starting_bid }}</b></p>
				<p><b>Current bid: ${{ listing.current_bid }}</b></p>
			 </div>
			 
			<a href="{% url 'auctions:title' listing.title %}" class="btn btn-primary">view details</a>
			
			</div>
        {% endfor %}
</div>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="listings">
	<h2>Watchlist</h2>
	{% for watchlist in watchlists %}
		 <div>
			 <h4>
				{{ watchlist.title }}
			</h4>
			 
			<a href="{% url 'auctions:title' watchlist.title %}" class="btn btn-primary">view details</a>

			<a href="{% url 'auctions:delete' watchlist.id %}" class="btn btn-danger">remove from watchlist</a>
		</div>
	{% endfor %}

</div>
{% endblock %}